model_type: ecd
input_features:
  - name: image_path
    type: image
    encoder:
      type: dinov2
      use_pretrained: true
      trainable: false
output_features:
  - name: label
    type: category
trainer:
  epochs: 10
  learning_rate: 0.001
