#
# Ludwig Docker image with basic set of pre-requiste packages and gpu-enabled Tensorflow
#

FROM tensorflow/tensorflow:latest-gpu-py3

RUN apt-get -y update && apt-get -y install git

RUN git clone --depth=1 https://github.com/uber/ludwig.git \
    && cd ludwig/ \
    && pip install -r requirements.txt \
    && python setup.py install

WORKDIR /data

ENTRYPOINT ["ludwig"]
