[pytest]
markers =
    benchmark: mark a test as a benchmarking test.
    distributed: mark a test as a distributed test.
    filesystem: mark to test operating system systems.
    slow: mark test as slow.
    combinatorial: mark a test as combinatorial.
    llm: mark a test as an LLM test.
    integration_tests_a: mark a test to be run as part of integration tests, group A.
    integration_tests_b: mark a test to be run as part of integration tests, group B.
    integration_tests_c: mark a test to be run as part of integration tests, group C.
    integration_tests_d: mark a test to be run as part of integration tests, group D.
    integration_tests_e: mark a test to be run as part of integration tests, group E.
    integration_tests_f: mark a test to be run as part of integration tests, group F.
    integration_tests_g: mark a test to be run as part of integration tests, group G.
    integration_tests_h: mark a test to be run as part of integration tests, group H.
    integration_tests_i: mark a test to be run as part of integration tests, group I.
    integration_tests_j: mark a test to be run as part of integration tests, group J.
    distributed_a: mark a distributed test to be run in distributed group A.
    distributed_b: mark a distributed test to be run in distributed group B.
    distributed_c: mark a distributed test to be run in distributed group C.
    distributed_d: mark a distributed test to be run in distributed group D.
    distributed_e: mark a distributed test to be run in distributed group E.
    distributed_f: mark a distributed test to be run in distributed group F.
filterwarnings =
    ignore::marshmallow.warnings.RemovedInMarshmallow4Warning
    ignore::DeprecationWarning:importlib._bootstrap
    ignore:builtin type Swig:DeprecationWarning
    ignore:.*torch.jit.script.*is deprecated:DeprecationWarning
