"""Auto-generate a model card from Ludwig training artifacts.

Produces a Markdown file summarizing the model architecture, training configuration, dataset characteristics, and
evaluation metrics. Saved automatically to the output directory after training.
"""

import logging
import platform
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


def generate_model_card(
    config: dict,
    training_set_metadata: dict,
    train_stats=None,
    model_dir: str | None = None,
    dataset_statistics: list | None = None,
) -> str:
    """Generate a Markdown model card from Ludwig training artifacts.

    Args:
        config: The full Ludwig config dict.
        training_set_metadata: Feature metadata computed during preprocessing.
        train_stats: Training statistics (train/validation/test metrics per epoch).
        model_dir: Path where the model is saved.
        dataset_statistics: Dataset split sizes.

    Returns:
        Markdown string.
    """
    lines = []
    lines.append("# Model Card")
    lines.append("")
    lines.append(f"Generated by Ludwig on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append("")

    # Model type
    model_type = config.get("model_type", "ecd")
    lines.append("## Model Type")
    lines.append("")
    lines.append(f"- **Type:** {model_type.upper()}")
    if "base_model" in config:
        lines.append(f"- **Base model:** {config['base_model']}")
    lines.append("")

    # Architecture
    lines.append("## Architecture")
    lines.append("")
    combiner = config.get("combiner", {})
    lines.append(f"- **Combiner:** {combiner.get('type', 'concat')}")
    for k, v in combiner.items():
        if k != "type":
            lines.append(f"  - {k}: {v}")
    lines.append("")

    # Input features
    lines.append("## Input Features")
    lines.append("")
    lines.append("| Name | Type | Encoder |")
    lines.append("|------|------|---------|")
    for feat in config.get("input_features", []):
        encoder = feat.get("encoder", {})
        enc_type = encoder.get("type", "default") if isinstance(encoder, dict) else str(encoder)
        lines.append(f"| {feat['name']} | {feat['type']} | {enc_type} |")
    lines.append("")

    # Output features
    lines.append("## Output Features")
    lines.append("")
    lines.append("| Name | Type | Decoder |")
    lines.append("|------|------|---------|")
    for feat in config.get("output_features", []):
        decoder = feat.get("decoder", {})
        dec_type = decoder.get("type", "default") if isinstance(decoder, dict) else str(decoder)
        lines.append(f"| {feat['name']} | {feat['type']} | {dec_type} |")
    lines.append("")

    # Training configuration
    trainer = config.get("trainer", {})
    if trainer:
        lines.append("## Training Configuration")
        lines.append("")
        for k in ["epochs", "batch_size", "learning_rate", "early_stop", "optimizer", "loss_balancing"]:
            if k in trainer:
                val = trainer[k]
                if isinstance(val, dict):
                    val = val.get("type", str(val))
                lines.append(f"- **{k}:** {val}")
        lines.append("")

    # Dataset statistics
    if dataset_statistics:
        lines.append("## Dataset")
        lines.append("")
        for row in dataset_statistics:
            if isinstance(row, (list, tuple)) and len(row) >= 2:
                lines.append(f"- **{row[0]}:** {row[1]}")
        lines.append("")

    # Feature metadata summary
    if training_set_metadata:
        lines.append("## Feature Statistics")
        lines.append("")
        for feat in config.get("input_features", []):
            feat_name = feat["name"]
            meta = training_set_metadata.get(feat_name, {})
            if isinstance(meta, dict):
                if "mean" in meta:
                    lines.append(f"- **{feat_name}:** mean={meta['mean']:.4f}, std={meta.get('std', 0):.4f}")
                elif "idx2str" in meta:
                    vocab_size = len(meta["idx2str"])
                    lines.append(f"- **{feat_name}:** {vocab_size} categories")
        lines.append("")

    # Evaluation metrics
    if train_stats is not None:
        lines.append("## Evaluation Metrics")
        lines.append("")
        for split_name, split_attr in [("Validation", "validation"), ("Test", "test")]:
            split_data = getattr(train_stats, split_attr, None)
            if split_data:
                lines.append(f"### {split_name}")
                lines.append("")
                for feat_name, feat_metrics in split_data.items():
                    if isinstance(feat_metrics, dict):
                        lines.append(f"**{feat_name}:**")
                        for metric_name, values in feat_metrics.items():
                            if isinstance(values, list) and values:
                                if "loss" in metric_name or "error" in metric_name:
                                    best = min(values)
                                else:
                                    best = max(values)
                                if isinstance(best, float):
                                    lines.append(f"- {metric_name}: {best:.6f}")
                        lines.append("")

    # Environment
    lines.append("## Environment")
    lines.append("")
    try:
        import ludwig

        lines.append(f"- **Ludwig version:** {ludwig.__version__}")
    except ImportError:
        pass
    try:
        import torch

        lines.append(f"- **PyTorch version:** {torch.__version__}")
        if torch.cuda.is_available():
            lines.append(f"- **GPU:** {torch.cuda.get_device_name(0)}")
    except ImportError:
        pass
    lines.append(f"- **Python:** {platform.python_version()}")
    lines.append(f"- **Platform:** {platform.platform()}")
    if model_dir:
        lines.append(f"- **Model path:** {model_dir}")
    lines.append("")

    return "\n".join(lines)


def save_model_card(
    output_directory: str,
    config: dict,
    training_set_metadata: dict,
    train_stats=None,
    model_dir: str | None = None,
    dataset_statistics: list | None = None,
):
    """Generate and save a model card to the output directory."""
    import os

    card = generate_model_card(
        config=config,
        training_set_metadata=training_set_metadata,
        train_stats=train_stats,
        model_dir=model_dir,
        dataset_statistics=dataset_statistics,
    )

    card_path = os.path.join(output_directory, "model_card.md")
    with open(card_path, "w") as f:
        f.write(card)

    logger.info(f"Model card saved to {card_path}")
    return card_path
