// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ludwig/profiling/proto/whylogs_messages.proto

package dataset_profile

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	_struct "github.com/golang/protobuf/ptypes/struct"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataType_Type int32

const (
	DataType_UNKNOWN    DataType_Type = 0
	DataType_NULL       DataType_Type = 1
	DataType_FRACTIONAL DataType_Type = 2
	DataType_INTEGRAL   DataType_Type = 3
	DataType_BOOLEAN    DataType_Type = 4
	DataType_STRING     DataType_Type = 5
)

var DataType_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "NULL",
	2: "FRACTIONAL",
	3: "INTEGRAL",
	4: "BOOLEAN",
	5: "STRING",
}

var DataType_Type_value = map[string]int32{
	"UNKNOWN":    0,
	"NULL":       1,
	"FRACTIONAL": 2,
	"INTEGRAL":   3,
	"BOOLEAN":    4,
	"STRING":     5,
}

func (x DataType_Type) String() string {
	return proto.EnumName(DataType_Type_name, int32(x))
}

func (DataType_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_27839e0967b539de, []int{0, 0}
}

type ChunkHeader_ChunkType int32

const (
	ChunkHeader_DATASET ChunkHeader_ChunkType = 0
	ChunkHeader_COLUMN  ChunkHeader_ChunkType = 2
)

var ChunkHeader_ChunkType_name = map[int32]string{
	0: "DATASET",
	2: "COLUMN",
}

var ChunkHeader_ChunkType_value = map[string]int32{
	"DATASET": 0,
	"COLUMN":  2,
}

func (x ChunkHeader_ChunkType) String() string {
	return proto.EnumName(ChunkHeader_ChunkType_name, int32(x))
}

func (ChunkHeader_ChunkType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_27839e0967b539de, []int{11, 0}
}

type DataType struct {
	Type                 DataType_Type `protobuf:"varint,1,opt,name=type,proto3,enum=dataset_profile.DataType_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DataType) Reset()         { *m = DataType{} }
func (m *DataType) String() string { return proto.CompactTextString(m) }
func (*DataType) ProtoMessage()    {}
func (*DataType) Descriptor() ([]byte, []int) {
	return fileDescriptor_27839e0967b539de, []int{0}
}

func (m *DataType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataType.Unmarshal(m, b)
}
func (m *DataType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataType.Marshal(b, m, deterministic)
}
func (m *DataType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataType.Merge(m, src)
}
func (m *DataType) XXX_Size() int {
	return xxx_messageInfo_DataType.Size(m)
}
func (m *DataType) XXX_DiscardUnknown() {
	xxx_messageInfo_DataType.DiscardUnknown(m)
}

var xxx_messageInfo_DataType proto.InternalMessageInfo

func (m *DataType) GetType() DataType_Type {
	if m != nil {
		return m.Type
	}
	return DataType_UNKNOWN
}

type HllSketchMessage struct {
	Sketch               []byte   `protobuf:"bytes,1,opt,name=sketch,proto3" json:"sketch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HllSketchMessage) Reset()         { *m = HllSketchMessage{} }
func (m *HllSketchMessage) String() string { return proto.CompactTextString(m) }
func (*HllSketchMessage) ProtoMessage()    {}
func (*HllSketchMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_27839e0967b539de, []int{1}
}

func (m *HllSketchMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HllSketchMessage.Unmarshal(m, b)
}
func (m *HllSketchMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HllSketchMessage.Marshal(b, m, deterministic)
}
func (m *HllSketchMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HllSketchMessage.Merge(m, src)
}
func (m *HllSketchMessage) XXX_Size() int {
	return xxx_messageInfo_HllSketchMessage.Size(m)
}
func (m *HllSketchMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_HllSketchMessage.DiscardUnknown(m)
}

var xxx_messageInfo_HllSketchMessage proto.InternalMessageInfo

func (m *HllSketchMessage) GetSketch() []byte {
	if m != nil {
		return m.Sketch
	}
	return nil
}

type FrequentItemsSketchMessage struct {
	Sketch               []byte   `protobuf:"bytes,1,opt,name=sketch,proto3" json:"sketch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrequentItemsSketchMessage) Reset()         { *m = FrequentItemsSketchMessage{} }
func (m *FrequentItemsSketchMessage) String() string { return proto.CompactTextString(m) }
func (*FrequentItemsSketchMessage) ProtoMessage()    {}
func (*FrequentItemsSketchMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_27839e0967b539de, []int{2}
}

func (m *FrequentItemsSketchMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrequentItemsSketchMessage.Unmarshal(m, b)
}
func (m *FrequentItemsSketchMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrequentItemsSketchMessage.Marshal(b, m, deterministic)
}
func (m *FrequentItemsSketchMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrequentItemsSketchMessage.Merge(m, src)
}
func (m *FrequentItemsSketchMessage) XXX_Size() int {
	return xxx_messageInfo_FrequentItemsSketchMessage.Size(m)
}
func (m *FrequentItemsSketchMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FrequentItemsSketchMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FrequentItemsSketchMessage proto.InternalMessageInfo

func (m *FrequentItemsSketchMessage) GetSketch() []byte {
	if m != nil {
		return m.Sketch
	}
	return nil
}

type KllSketchMessage struct {
	Sketch               []byte   `protobuf:"bytes,1,opt,name=sketch,proto3" json:"sketch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KllSketchMessage) Reset()         { *m = KllSketchMessage{} }
func (m *KllSketchMessage) String() string { return proto.CompactTextString(m) }
func (*KllSketchMessage) ProtoMessage()    {}
func (*KllSketchMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_27839e0967b539de, []int{3}
}

func (m *KllSketchMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KllSketchMessage.Unmarshal(m, b)
}
func (m *KllSketchMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KllSketchMessage.Marshal(b, m, deterministic)
}
func (m *KllSketchMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KllSketchMessage.Merge(m, src)
}
func (m *KllSketchMessage) XXX_Size() int {
	return xxx_messageInfo_KllSketchMessage.Size(m)
}
func (m *KllSketchMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_KllSketchMessage.DiscardUnknown(m)
}

var xxx_messageInfo_KllSketchMessage proto.InternalMessageInfo

func (m *KllSketchMessage) GetSketch() []byte {
	if m != nil {
		return m.Sketch
	}
	return nil
}

type CpcSketchMessage struct {
	Sketch               []byte   `protobuf:"bytes,1,opt,name=sketch,proto3" json:"sketch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CpcSketchMessage) Reset()         { *m = CpcSketchMessage{} }
func (m *CpcSketchMessage) String() string { return proto.CompactTextString(m) }
func (*CpcSketchMessage) ProtoMessage()    {}
func (*CpcSketchMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_27839e0967b539de, []int{4}
}

func (m *CpcSketchMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CpcSketchMessage.Unmarshal(m, b)
}
func (m *CpcSketchMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CpcSketchMessage.Marshal(b, m, deterministic)
}
func (m *CpcSketchMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CpcSketchMessage.Merge(m, src)
}
func (m *CpcSketchMessage) XXX_Size() int {
	return xxx_messageInfo_CpcSketchMessage.Size(m)
}
func (m *CpcSketchMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CpcSketchMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CpcSketchMessage proto.InternalMessageInfo

func (m *CpcSketchMessage) GetSketch() []byte {
	if m != nil {
		return m.Sketch
	}
	return nil
}

type MetricComponentMessage struct {
	TypeId uint32 `protobuf:"varint,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*MetricComponentMessage_N
	//	*MetricComponentMessage_D
	//	*MetricComponentMessage_FrequentItems
	//	*MetricComponentMessage_Hll
	//	*MetricComponentMessage_Kll
	//	*MetricComponentMessage_Cpc
	//	*MetricComponentMessage_SerializedBytes
	//	*MetricComponentMessage_DataclassParam
	//	*MetricComponentMessage_Msg
	Value                isMetricComponentMessage_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *MetricComponentMessage) Reset()         { *m = MetricComponentMessage{} }
func (m *MetricComponentMessage) String() string { return proto.CompactTextString(m) }
func (*MetricComponentMessage) ProtoMessage()    {}
func (*MetricComponentMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_27839e0967b539de, []int{5}
}

func (m *MetricComponentMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricComponentMessage.Unmarshal(m, b)
}
func (m *MetricComponentMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricComponentMessage.Marshal(b, m, deterministic)
}
func (m *MetricComponentMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricComponentMessage.Merge(m, src)
}
func (m *MetricComponentMessage) XXX_Size() int {
	return xxx_messageInfo_MetricComponentMessage.Size(m)
}
func (m *MetricComponentMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricComponentMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MetricComponentMessage proto.InternalMessageInfo

func (m *MetricComponentMessage) GetTypeId() uint32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

type isMetricComponentMessage_Value interface {
	isMetricComponentMessage_Value()
}

type MetricComponentMessage_N struct {
	N int64 `protobuf:"varint,2,opt,name=n,proto3,oneof"`
}

type MetricComponentMessage_D struct {
	D float64 `protobuf:"fixed64,3,opt,name=d,proto3,oneof"`
}

type MetricComponentMessage_FrequentItems struct {
	FrequentItems *FrequentItemsSketchMessage `protobuf:"bytes,4,opt,name=frequent_items,json=frequentItems,proto3,oneof"`
}

type MetricComponentMessage_Hll struct {
	Hll *HllSketchMessage `protobuf:"bytes,5,opt,name=hll,proto3,oneof"`
}

type MetricComponentMessage_Kll struct {
	Kll *KllSketchMessage `protobuf:"bytes,6,opt,name=kll,proto3,oneof"`
}

type MetricComponentMessage_Cpc struct {
	Cpc *CpcSketchMessage `protobuf:"bytes,7,opt,name=cpc,proto3,oneof"`
}

type MetricComponentMessage_SerializedBytes struct {
	SerializedBytes []byte `protobuf:"bytes,10,opt,name=serialized_bytes,json=serializedBytes,proto3,oneof"`
}

type MetricComponentMessage_DataclassParam struct {
	DataclassParam *_struct.Struct `protobuf:"bytes,11,opt,name=dataclass_param,json=dataclassParam,proto3,oneof"`
}

type MetricComponentMessage_Msg struct {
	Msg *any.Any `protobuf:"bytes,12,opt,name=msg,proto3,oneof"`
}

func (*MetricComponentMessage_N) isMetricComponentMessage_Value() {}

func (*MetricComponentMessage_D) isMetricComponentMessage_Value() {}

func (*MetricComponentMessage_FrequentItems) isMetricComponentMessage_Value() {}

func (*MetricComponentMessage_Hll) isMetricComponentMessage_Value() {}

func (*MetricComponentMessage_Kll) isMetricComponentMessage_Value() {}

func (*MetricComponentMessage_Cpc) isMetricComponentMessage_Value() {}

func (*MetricComponentMessage_SerializedBytes) isMetricComponentMessage_Value() {}

func (*MetricComponentMessage_DataclassParam) isMetricComponentMessage_Value() {}

func (*MetricComponentMessage_Msg) isMetricComponentMessage_Value() {}

func (m *MetricComponentMessage) GetValue() isMetricComponentMessage_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *MetricComponentMessage) GetN() int64 {
	if x, ok := m.GetValue().(*MetricComponentMessage_N); ok {
		return x.N
	}
	return 0
}

func (m *MetricComponentMessage) GetD() float64 {
	if x, ok := m.GetValue().(*MetricComponentMessage_D); ok {
		return x.D
	}
	return 0
}

func (m *MetricComponentMessage) GetFrequentItems() *FrequentItemsSketchMessage {
	if x, ok := m.GetValue().(*MetricComponentMessage_FrequentItems); ok {
		return x.FrequentItems
	}
	return nil
}

func (m *MetricComponentMessage) GetHll() *HllSketchMessage {
	if x, ok := m.GetValue().(*MetricComponentMessage_Hll); ok {
		return x.Hll
	}
	return nil
}

func (m *MetricComponentMessage) GetKll() *KllSketchMessage {
	if x, ok := m.GetValue().(*MetricComponentMessage_Kll); ok {
		return x.Kll
	}
	return nil
}

func (m *MetricComponentMessage) GetCpc() *CpcSketchMessage {
	if x, ok := m.GetValue().(*MetricComponentMessage_Cpc); ok {
		return x.Cpc
	}
	return nil
}

func (m *MetricComponentMessage) GetSerializedBytes() []byte {
	if x, ok := m.GetValue().(*MetricComponentMessage_SerializedBytes); ok {
		return x.SerializedBytes
	}
	return nil
}

func (m *MetricComponentMessage) GetDataclassParam() *_struct.Struct {
	if x, ok := m.GetValue().(*MetricComponentMessage_DataclassParam); ok {
		return x.DataclassParam
	}
	return nil
}

func (m *MetricComponentMessage) GetMsg() *any.Any {
	if x, ok := m.GetValue().(*MetricComponentMessage_Msg); ok {
		return x.Msg
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MetricComponentMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MetricComponentMessage_N)(nil),
		(*MetricComponentMessage_D)(nil),
		(*MetricComponentMessage_FrequentItems)(nil),
		(*MetricComponentMessage_Hll)(nil),
		(*MetricComponentMessage_Kll)(nil),
		(*MetricComponentMessage_Cpc)(nil),
		(*MetricComponentMessage_SerializedBytes)(nil),
		(*MetricComponentMessage_DataclassParam)(nil),
		(*MetricComponentMessage_Msg)(nil),
	}
}

type MetricMessage struct {
	MetricComponents     map[string]*MetricComponentMessage `protobuf:"bytes,1,rep,name=metric_components,json=metricComponents,proto3" json:"metric_components,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *MetricMessage) Reset()         { *m = MetricMessage{} }
func (m *MetricMessage) String() string { return proto.CompactTextString(m) }
func (*MetricMessage) ProtoMessage()    {}
func (*MetricMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_27839e0967b539de, []int{6}
}

func (m *MetricMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricMessage.Unmarshal(m, b)
}
func (m *MetricMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricMessage.Marshal(b, m, deterministic)
}
func (m *MetricMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricMessage.Merge(m, src)
}
func (m *MetricMessage) XXX_Size() int {
	return xxx_messageInfo_MetricMessage.Size(m)
}
func (m *MetricMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MetricMessage proto.InternalMessageInfo

func (m *MetricMessage) GetMetricComponents() map[string]*MetricComponentMessage {
	if m != nil {
		return m.MetricComponents
	}
	return nil
}

type ColumnMessage struct {
	MetricComponents     map[string]*MetricComponentMessage `protobuf:"bytes,1,rep,name=metric_components,json=metricComponents,proto3" json:"metric_components,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *ColumnMessage) Reset()         { *m = ColumnMessage{} }
func (m *ColumnMessage) String() string { return proto.CompactTextString(m) }
func (*ColumnMessage) ProtoMessage()    {}
func (*ColumnMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_27839e0967b539de, []int{7}
}

func (m *ColumnMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColumnMessage.Unmarshal(m, b)
}
func (m *ColumnMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColumnMessage.Marshal(b, m, deterministic)
}
func (m *ColumnMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColumnMessage.Merge(m, src)
}
func (m *ColumnMessage) XXX_Size() int {
	return xxx_messageInfo_ColumnMessage.Size(m)
}
func (m *ColumnMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ColumnMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ColumnMessage proto.InternalMessageInfo

func (m *ColumnMessage) GetMetricComponents() map[string]*MetricComponentMessage {
	if m != nil {
		return m.MetricComponents
	}
	return nil
}

type DatasetProperties struct {
	SchemaMajorVersion   uint32            `protobuf:"varint,1,opt,name=schema_major_version,json=schemaMajorVersion,proto3" json:"schema_major_version,omitempty"`
	SchemaMinorVersion   uint32            `protobuf:"varint,2,opt,name=schema_minor_version,json=schemaMinorVersion,proto3" json:"schema_minor_version,omitempty"`
	CreationTimestamp    uint64            `protobuf:"varint,4,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"`
	DatasetTimestamp     uint64            `protobuf:"varint,5,opt,name=dataset_timestamp,json=datasetTimestamp,proto3" json:"dataset_timestamp,omitempty"`
	Tags                 map[string]string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Metadata             map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DatasetProperties) Reset()         { *m = DatasetProperties{} }
func (m *DatasetProperties) String() string { return proto.CompactTextString(m) }
func (*DatasetProperties) ProtoMessage()    {}
func (*DatasetProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_27839e0967b539de, []int{8}
}

func (m *DatasetProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatasetProperties.Unmarshal(m, b)
}
func (m *DatasetProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatasetProperties.Marshal(b, m, deterministic)
}
func (m *DatasetProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatasetProperties.Merge(m, src)
}
func (m *DatasetProperties) XXX_Size() int {
	return xxx_messageInfo_DatasetProperties.Size(m)
}
func (m *DatasetProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_DatasetProperties.DiscardUnknown(m)
}

var xxx_messageInfo_DatasetProperties proto.InternalMessageInfo

func (m *DatasetProperties) GetSchemaMajorVersion() uint32 {
	if m != nil {
		return m.SchemaMajorVersion
	}
	return 0
}

func (m *DatasetProperties) GetSchemaMinorVersion() uint32 {
	if m != nil {
		return m.SchemaMinorVersion
	}
	return 0
}

func (m *DatasetProperties) GetCreationTimestamp() uint64 {
	if m != nil {
		return m.CreationTimestamp
	}
	return 0
}

func (m *DatasetProperties) GetDatasetTimestamp() uint64 {
	if m != nil {
		return m.DatasetTimestamp
	}
	return 0
}

func (m *DatasetProperties) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *DatasetProperties) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ChunkOffsets struct {
	Offsets              []uint64 `protobuf:"varint,1,rep,packed,name=offsets,proto3" json:"offsets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChunkOffsets) Reset()         { *m = ChunkOffsets{} }
func (m *ChunkOffsets) String() string { return proto.CompactTextString(m) }
func (*ChunkOffsets) ProtoMessage()    {}
func (*ChunkOffsets) Descriptor() ([]byte, []int) {
	return fileDescriptor_27839e0967b539de, []int{9}
}

func (m *ChunkOffsets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChunkOffsets.Unmarshal(m, b)
}
func (m *ChunkOffsets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChunkOffsets.Marshal(b, m, deterministic)
}
func (m *ChunkOffsets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChunkOffsets.Merge(m, src)
}
func (m *ChunkOffsets) XXX_Size() int {
	return xxx_messageInfo_ChunkOffsets.Size(m)
}
func (m *ChunkOffsets) XXX_DiscardUnknown() {
	xxx_messageInfo_ChunkOffsets.DiscardUnknown(m)
}

var xxx_messageInfo_ChunkOffsets proto.InternalMessageInfo

func (m *ChunkOffsets) GetOffsets() []uint64 {
	if m != nil {
		return m.Offsets
	}
	return nil
}

type ChunkMessage struct {
	MetricComponents     map[uint32]*MetricComponentMessage `protobuf:"bytes,1,rep,name=metric_components,json=metricComponents,proto3" json:"metric_components,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *ChunkMessage) Reset()         { *m = ChunkMessage{} }
func (m *ChunkMessage) String() string { return proto.CompactTextString(m) }
func (*ChunkMessage) ProtoMessage()    {}
func (*ChunkMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_27839e0967b539de, []int{10}
}

func (m *ChunkMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChunkMessage.Unmarshal(m, b)
}
func (m *ChunkMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChunkMessage.Marshal(b, m, deterministic)
}
func (m *ChunkMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChunkMessage.Merge(m, src)
}
func (m *ChunkMessage) XXX_Size() int {
	return xxx_messageInfo_ChunkMessage.Size(m)
}
func (m *ChunkMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChunkMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChunkMessage proto.InternalMessageInfo

func (m *ChunkMessage) GetMetricComponents() map[uint32]*MetricComponentMessage {
	if m != nil {
		return m.MetricComponents
	}
	return nil
}

type ChunkHeader struct {
	Type                 ChunkHeader_ChunkType `protobuf:"varint,1,opt,name=type,proto3,enum=dataset_profile.ChunkHeader_ChunkType" json:"type,omitempty"`
	Tag                  string                `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Length               uint32                `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ChunkHeader) Reset()         { *m = ChunkHeader{} }
func (m *ChunkHeader) String() string { return proto.CompactTextString(m) }
func (*ChunkHeader) ProtoMessage()    {}
func (*ChunkHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_27839e0967b539de, []int{11}
}

func (m *ChunkHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChunkHeader.Unmarshal(m, b)
}
func (m *ChunkHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChunkHeader.Marshal(b, m, deterministic)
}
func (m *ChunkHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChunkHeader.Merge(m, src)
}
func (m *ChunkHeader) XXX_Size() int {
	return xxx_messageInfo_ChunkHeader.Size(m)
}
func (m *ChunkHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ChunkHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ChunkHeader proto.InternalMessageInfo

func (m *ChunkHeader) GetType() ChunkHeader_ChunkType {
	if m != nil {
		return m.Type
	}
	return ChunkHeader_DATASET
}

func (m *ChunkHeader) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *ChunkHeader) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

type DatasetProfileHeader struct {
	Properties           *DatasetProperties       `protobuf:"bytes,1,opt,name=properties,proto3" json:"properties,omitempty"`
	ColumnOffsets        map[string]*ChunkOffsets `protobuf:"bytes,2,rep,name=column_offsets,json=columnOffsets,proto3" json:"column_offsets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MetricOffsets        []*ChunkOffsets          `protobuf:"bytes,3,rep,name=metric_offsets,json=metricOffsets,proto3" json:"metric_offsets,omitempty"`
	Length               uint64                   `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	IndexedMetricPaths   map[uint32]string        `protobuf:"bytes,5,rep,name=indexed_metric_paths,json=indexedMetricPaths,proto3" json:"indexed_metric_paths,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *DatasetProfileHeader) Reset()         { *m = DatasetProfileHeader{} }
func (m *DatasetProfileHeader) String() string { return proto.CompactTextString(m) }
func (*DatasetProfileHeader) ProtoMessage()    {}
func (*DatasetProfileHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_27839e0967b539de, []int{12}
}

func (m *DatasetProfileHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatasetProfileHeader.Unmarshal(m, b)
}
func (m *DatasetProfileHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatasetProfileHeader.Marshal(b, m, deterministic)
}
func (m *DatasetProfileHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatasetProfileHeader.Merge(m, src)
}
func (m *DatasetProfileHeader) XXX_Size() int {
	return xxx_messageInfo_DatasetProfileHeader.Size(m)
}
func (m *DatasetProfileHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_DatasetProfileHeader.DiscardUnknown(m)
}

var xxx_messageInfo_DatasetProfileHeader proto.InternalMessageInfo

func (m *DatasetProfileHeader) GetProperties() *DatasetProperties {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *DatasetProfileHeader) GetColumnOffsets() map[string]*ChunkOffsets {
	if m != nil {
		return m.ColumnOffsets
	}
	return nil
}

func (m *DatasetProfileHeader) GetMetricOffsets() []*ChunkOffsets {
	if m != nil {
		return m.MetricOffsets
	}
	return nil
}

func (m *DatasetProfileHeader) GetLength() uint64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *DatasetProfileHeader) GetIndexedMetricPaths() map[uint32]string {
	if m != nil {
		return m.IndexedMetricPaths
	}
	return nil
}

type SegmentTag struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegmentTag) Reset()         { *m = SegmentTag{} }
func (m *SegmentTag) String() string { return proto.CompactTextString(m) }
func (*SegmentTag) ProtoMessage()    {}
func (*SegmentTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_27839e0967b539de, []int{13}
}

func (m *SegmentTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentTag.Unmarshal(m, b)
}
func (m *SegmentTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentTag.Marshal(b, m, deterministic)
}
func (m *SegmentTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentTag.Merge(m, src)
}
func (m *SegmentTag) XXX_Size() int {
	return xxx_messageInfo_SegmentTag.Size(m)
}
func (m *SegmentTag) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentTag.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentTag proto.InternalMessageInfo

func (m *SegmentTag) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SegmentTag) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Segment struct {
	Tags                 []*SegmentTag `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Segment) Reset()         { *m = Segment{} }
func (m *Segment) String() string { return proto.CompactTextString(m) }
func (*Segment) ProtoMessage()    {}
func (*Segment) Descriptor() ([]byte, []int) {
	return fileDescriptor_27839e0967b539de, []int{14}
}

func (m *Segment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Segment.Unmarshal(m, b)
}
func (m *Segment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Segment.Marshal(b, m, deterministic)
}
func (m *Segment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Segment.Merge(m, src)
}
func (m *Segment) XXX_Size() int {
	return xxx_messageInfo_Segment.Size(m)
}
func (m *Segment) XXX_DiscardUnknown() {
	xxx_messageInfo_Segment.DiscardUnknown(m)
}

var xxx_messageInfo_Segment proto.InternalMessageInfo

func (m *Segment) GetTags() []*SegmentTag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type DatasetSegmentHeader struct {
	// whether the file contains segmented data or not
	HasSegments bool `protobuf:"varint,1,opt,name=has_segments,json=hasSegments,proto3" json:"has_segments,omitempty"`
	// list of segments
	Segments []*Segment `protobuf:"bytes,4,rep,name=segments,proto3" json:"segments,omitempty"`
	// we want the indices of the map of offsets to have static size, and thus we use fixed32 bytes
	Offsets              map[uint32]uint64 `protobuf:"bytes,5,rep,name=offsets,proto3" json:"offsets,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DatasetSegmentHeader) Reset()         { *m = DatasetSegmentHeader{} }
func (m *DatasetSegmentHeader) String() string { return proto.CompactTextString(m) }
func (*DatasetSegmentHeader) ProtoMessage()    {}
func (*DatasetSegmentHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_27839e0967b539de, []int{15}
}

func (m *DatasetSegmentHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatasetSegmentHeader.Unmarshal(m, b)
}
func (m *DatasetSegmentHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatasetSegmentHeader.Marshal(b, m, deterministic)
}
func (m *DatasetSegmentHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatasetSegmentHeader.Merge(m, src)
}
func (m *DatasetSegmentHeader) XXX_Size() int {
	return xxx_messageInfo_DatasetSegmentHeader.Size(m)
}
func (m *DatasetSegmentHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_DatasetSegmentHeader.DiscardUnknown(m)
}

var xxx_messageInfo_DatasetSegmentHeader proto.InternalMessageInfo

func (m *DatasetSegmentHeader) GetHasSegments() bool {
	if m != nil {
		return m.HasSegments
	}
	return false
}

func (m *DatasetSegmentHeader) GetSegments() []*Segment {
	if m != nil {
		return m.Segments
	}
	return nil
}

func (m *DatasetSegmentHeader) GetOffsets() map[uint32]uint64 {
	if m != nil {
		return m.Offsets
	}
	return nil
}

func init() {
	proto.RegisterEnum("dataset_profile.DataType_Type", DataType_Type_name, DataType_Type_value)
	proto.RegisterEnum("dataset_profile.ChunkHeader_ChunkType", ChunkHeader_ChunkType_name, ChunkHeader_ChunkType_value)
	proto.RegisterType((*DataType)(nil), "dataset_profile.DataType")
	proto.RegisterType((*HllSketchMessage)(nil), "dataset_profile.HllSketchMessage")
	proto.RegisterType((*FrequentItemsSketchMessage)(nil), "dataset_profile.FrequentItemsSketchMessage")
	proto.RegisterType((*KllSketchMessage)(nil), "dataset_profile.KllSketchMessage")
	proto.RegisterType((*CpcSketchMessage)(nil), "dataset_profile.CpcSketchMessage")
	proto.RegisterType((*MetricComponentMessage)(nil), "dataset_profile.MetricComponentMessage")
	proto.RegisterType((*MetricMessage)(nil), "dataset_profile.MetricMessage")
	proto.RegisterMapType((map[string]*MetricComponentMessage)(nil), "dataset_profile.MetricMessage.MetricComponentsEntry")
	proto.RegisterType((*ColumnMessage)(nil), "dataset_profile.ColumnMessage")
	proto.RegisterMapType((map[string]*MetricComponentMessage)(nil), "dataset_profile.ColumnMessage.MetricComponentsEntry")
	proto.RegisterType((*DatasetProperties)(nil), "dataset_profile.DatasetProperties")
	proto.RegisterMapType((map[string]string)(nil), "dataset_profile.DatasetProperties.MetadataEntry")
	proto.RegisterMapType((map[string]string)(nil), "dataset_profile.DatasetProperties.TagsEntry")
	proto.RegisterType((*ChunkOffsets)(nil), "dataset_profile.ChunkOffsets")
	proto.RegisterType((*ChunkMessage)(nil), "dataset_profile.ChunkMessage")
	proto.RegisterMapType((map[uint32]*MetricComponentMessage)(nil), "dataset_profile.ChunkMessage.MetricComponentsEntry")
	proto.RegisterType((*ChunkHeader)(nil), "dataset_profile.ChunkHeader")
	proto.RegisterType((*DatasetProfileHeader)(nil), "dataset_profile.DatasetProfileHeader")
	proto.RegisterMapType((map[string]*ChunkOffsets)(nil), "dataset_profile.DatasetProfileHeader.ColumnOffsetsEntry")
	proto.RegisterMapType((map[uint32]string)(nil), "dataset_profile.DatasetProfileHeader.IndexedMetricPathsEntry")
	proto.RegisterType((*SegmentTag)(nil), "dataset_profile.SegmentTag")
	proto.RegisterType((*Segment)(nil), "dataset_profile.Segment")
	proto.RegisterType((*DatasetSegmentHeader)(nil), "dataset_profile.DatasetSegmentHeader")
	proto.RegisterMapType((map[uint32]uint64)(nil), "dataset_profile.DatasetSegmentHeader.OffsetsEntry")
}

func init() {
	proto.RegisterFile("ludwig/profiling/proto/whylogs_messages.proto", fileDescriptor_27839e0967b539de)
}

var fileDescriptor_27839e0967b539de = []byte{
	// 1138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x5b, 0x6f, 0x1b, 0x45,
	0x14, 0xf6, 0xda, 0x8e, 0xed, 0x1c, 0x5f, 0xba, 0x19, 0x85, 0x76, 0x31, 0x17, 0xa5, 0x2b, 0x04,
	0x56, 0x4b, 0x9d, 0xca, 0x0d, 0xa2, 0x0a, 0xaa, 0x84, 0xe3, 0xa4, 0xb5, 0x55, 0xc7, 0xae, 0x36,
	0x0e, 0x3c, 0x2e, 0x93, 0xf5, 0x78, 0xbd, 0x64, 0x6f, 0xec, 0x8c, 0x5b, 0xcc, 0xef, 0xe0, 0x85,
	0xbf, 0xc1, 0xbf, 0xe1, 0x05, 0xf1, 0x13, 0x78, 0xe5, 0x0d, 0xcd, 0xcc, 0xae, 0xef, 0xa6, 0x06,
	0xf5, 0x81, 0x17, 0x6b, 0x67, 0xce, 0xf9, 0xce, 0xf5, 0x3b, 0x67, 0x0c, 0x8f, 0xdc, 0xc9, 0xf0,
	0x8d, 0x63, 0x1f, 0x87, 0x51, 0x30, 0x72, 0x5c, 0xc7, 0x17, 0x5f, 0x2c, 0x38, 0x7e, 0x33, 0x9e,
	0xba, 0x81, 0x4d, 0x4d, 0x8f, 0x50, 0x8a, 0x6d, 0x42, 0xeb, 0xe2, 0x1a, 0xdd, 0x19, 0x62, 0x86,
	0x29, 0x61, 0xa6, 0xd4, 0x27, 0xd5, 0xf7, 0xed, 0x20, 0xb0, 0x5d, 0x22, 0x51, 0x37, 0x93, 0xd1,
	0x31, 0xf6, 0xa7, 0x52, 0xb7, 0xfa, 0xe1, 0xaa, 0x88, 0xb2, 0x68, 0x62, 0x31, 0x29, 0xd5, 0x7f,
	0x56, 0xa0, 0x70, 0x8e, 0x19, 0x1e, 0x4c, 0x43, 0x82, 0x1a, 0x90, 0x65, 0xd3, 0x90, 0x68, 0xca,
	0x91, 0x52, 0xab, 0x34, 0x3e, 0xae, 0xaf, 0x78, 0xa9, 0x27, 0x8a, 0x75, 0xfe, 0x63, 0x08, 0x5d,
	0x7d, 0x00, 0x59, 0x81, 0x2d, 0x42, 0xfe, 0xba, 0xf7, 0xb2, 0xd7, 0xff, 0xb6, 0xa7, 0xa6, 0x50,
	0x01, 0xb2, 0xbd, 0xeb, 0x6e, 0x57, 0x55, 0x50, 0x05, 0xe0, 0xb9, 0xd1, 0x6c, 0x0d, 0x3a, 0xfd,
	0x5e, 0xb3, 0xab, 0xa6, 0x51, 0x09, 0x0a, 0x9d, 0xde, 0xe0, 0xe2, 0x85, 0xd1, 0xec, 0xaa, 0x19,
	0x0e, 0x3a, 0xeb, 0xf7, 0xbb, 0x17, 0xcd, 0x9e, 0x9a, 0x45, 0x00, 0xb9, 0xab, 0x81, 0xd1, 0xe9,
	0xbd, 0x50, 0xf7, 0xf4, 0x07, 0xa0, 0xb6, 0x5d, 0xf7, 0xea, 0x96, 0x30, 0x6b, 0x7c, 0x29, 0x73,
	0x47, 0x77, 0x21, 0x47, 0xc5, 0x85, 0x88, 0xaf, 0x64, 0xc4, 0x27, 0xfd, 0x04, 0xaa, 0xcf, 0x23,
	0xf2, 0xc3, 0x84, 0xf8, 0xac, 0xc3, 0x88, 0x47, 0x77, 0x43, 0x3d, 0x00, 0xf5, 0xe5, 0xae, 0x1e,
	0x1e, 0x80, 0xda, 0x0a, 0xad, 0xdd, 0x74, 0xff, 0xcc, 0xc0, 0xdd, 0x4b, 0xc2, 0x22, 0xc7, 0x6a,
	0x05, 0x5e, 0x18, 0xf8, 0xc4, 0x67, 0x09, 0xe4, 0x1e, 0xe4, 0x79, 0xc9, 0x4c, 0x67, 0x28, 0x30,
	0x65, 0x23, 0xc7, 0x8f, 0x9d, 0x21, 0xaa, 0x80, 0xe2, 0x6b, 0xe9, 0x23, 0xa5, 0x96, 0x69, 0xa7,
	0x0c, 0xc5, 0xe7, 0xe7, 0xa1, 0x96, 0x39, 0x52, 0x6a, 0x0a, 0x3f, 0x0f, 0xd1, 0x00, 0x2a, 0xa3,
	0x38, 0x43, 0xd3, 0xe1, 0x29, 0x6a, 0xd9, 0x23, 0xa5, 0x56, 0x6c, 0x3c, 0x5c, 0xeb, 0xd0, 0xf6,
	0x42, 0xb4, 0x53, 0x46, 0x79, 0xb4, 0x28, 0x45, 0x5f, 0x40, 0x66, 0xec, 0xba, 0xda, 0x9e, 0x30,
	0x75, 0x7f, 0xcd, 0xd4, 0x6a, 0xfd, 0xdb, 0x29, 0x83, 0xeb, 0x73, 0xd8, 0xad, 0xeb, 0x6a, 0xb9,
	0x2d, 0xb0, 0x97, 0x1b, 0x60, 0xb7, 0x12, 0x66, 0x85, 0x96, 0x96, 0xdf, 0x02, 0x5b, 0xad, 0x2f,
	0x87, 0x59, 0xa1, 0x85, 0x1e, 0x82, 0x4a, 0x49, 0xe4, 0x60, 0xd7, 0xf9, 0x89, 0x0c, 0xcd, 0x9b,
	0x29, 0x23, 0x54, 0x03, 0x5e, 0xf0, 0x76, 0xca, 0xb8, 0x33, 0x97, 0x9c, 0x71, 0x01, 0x3a, 0x03,
	0x31, 0x18, 0x96, 0x8b, 0x29, 0x35, 0x43, 0x1c, 0x61, 0x4f, 0x2b, 0x0a, 0x7f, 0xf7, 0xea, 0x72,
	0x08, 0xea, 0xc9, 0x10, 0xd4, 0xaf, 0xc4, 0x10, 0xb4, 0x53, 0x46, 0x65, 0x86, 0x78, 0xc5, 0x01,
	0xa8, 0x06, 0x19, 0x8f, 0xda, 0x5a, 0x49, 0xe0, 0x0e, 0xd7, 0x70, 0x4d, 0x7f, 0xca, 0x43, 0xf3,
	0xa8, 0x7d, 0x96, 0x87, 0xbd, 0xd7, 0xd8, 0x9d, 0x10, 0xfd, 0x0f, 0x05, 0xca, 0xb2, 0xe5, 0x49,
	0xa7, 0x31, 0x1c, 0x78, 0xe2, 0xc2, 0xb4, 0x12, 0x12, 0x50, 0x4d, 0x39, 0xca, 0xd4, 0x8a, 0x8d,
	0x93, 0xb5, 0xd4, 0x97, 0xa0, 0xf5, 0x15, 0xee, 0xd0, 0x0b, 0x9f, 0x45, 0x53, 0x43, 0xf5, 0x56,
	0xae, 0xab, 0x2e, 0xbc, 0xb7, 0x51, 0x15, 0xa9, 0x90, 0xb9, 0x25, 0x53, 0xc1, 0xb0, 0x7d, 0x83,
	0x7f, 0xa2, 0x67, 0x71, 0xa0, 0x82, 0x62, 0xc5, 0xc6, 0x67, 0x5b, 0x22, 0x58, 0xe5, 0xab, 0x21,
	0x51, 0xa7, 0xe9, 0xa7, 0x8a, 0x48, 0xb1, 0x15, 0xb8, 0x13, 0xcf, 0xff, 0x4f, 0x29, 0x2e, 0x41,
	0xff, 0xa7, 0x29, 0xfe, 0x96, 0x81, 0x83, 0x73, 0x89, 0x7a, 0x15, 0x05, 0x21, 0x89, 0x98, 0x43,
	0x28, 0x7a, 0x0c, 0x87, 0xd4, 0x1a, 0x13, 0x0f, 0x9b, 0x1e, 0xfe, 0x3e, 0x88, 0xcc, 0xd7, 0x24,
	0xa2, 0x4e, 0xe0, 0xc7, 0x03, 0x8c, 0xa4, 0xec, 0x92, 0x8b, 0xbe, 0x91, 0x92, 0x45, 0x84, 0xe3,
	0x2f, 0x20, 0xd2, 0x4b, 0x08, 0x2e, 0x4a, 0x10, 0x8f, 0x00, 0x59, 0x11, 0xc1, 0xcc, 0x09, 0x7c,
	0x93, 0x39, 0x1e, 0xa1, 0x0c, 0x7b, 0xa1, 0x18, 0xf1, 0xac, 0x71, 0x90, 0x48, 0x06, 0x89, 0x00,
	0x3d, 0x84, 0x83, 0x24, 0xbb, 0xb9, 0xf6, 0x9e, 0xd0, 0x56, 0x63, 0xc1, 0x5c, 0xf9, 0x6b, 0xc8,
	0x32, 0x6c, 0x53, 0x2d, 0x27, 0x3a, 0xf3, 0xf9, 0xc6, 0x95, 0xbe, 0x94, 0x71, 0x7d, 0x80, 0xed,
	0xb8, 0x23, 0x02, 0x89, 0xba, 0x50, 0xf0, 0x08, 0xc3, 0x1c, 0xa8, 0xe5, 0x85, 0x95, 0xc7, 0x3b,
	0x58, 0xb9, 0x8c, 0x21, 0xd2, 0xd2, 0xcc, 0x42, 0xf5, 0x4b, 0xd8, 0x9f, 0x39, 0xd8, 0xd0, 0xc7,
	0xc3, 0xc5, 0x3e, 0xee, 0x2f, 0xb4, 0xa7, 0xfa, 0x95, 0x98, 0xb1, 0xb9, 0xcd, 0x7f, 0x03, 0xd6,
	0x6b, 0x50, 0x6a, 0x8d, 0x27, 0xfe, 0x6d, 0x7f, 0x34, 0xa2, 0x84, 0x51, 0xa4, 0x41, 0x3e, 0x90,
	0x9f, 0x82, 0xb2, 0x59, 0x23, 0x39, 0xea, 0xbf, 0x2b, 0xb1, 0x6a, 0xc2, 0xf3, 0xef, 0xb6, 0xf3,
	0xfc, 0xc9, 0x3a, 0xcf, 0x17, 0x90, 0xef, 0x94, 0xe6, 0xe5, 0x77, 0x46, 0xf3, 0x5f, 0x14, 0x28,
	0x8a, 0x30, 0xdb, 0x04, 0x0f, 0x49, 0x84, 0x4e, 0x97, 0xde, 0xfc, 0x4f, 0x37, 0xa7, 0x24, 0x75,
	0xe5, 0xf7, 0xfc, 0xed, 0xe7, 0x01, 0x32, 0x6c, 0xc7, 0xe5, 0xe6, 0x9f, 0xfc, 0x55, 0x74, 0x89,
	0x6f, 0xb3, 0xb1, 0x78, 0xbe, 0xca, 0x46, 0x7c, 0xd2, 0x3f, 0x81, 0xfd, 0x19, 0x98, 0xbf, 0xfa,
	0xe7, 0xcd, 0x41, 0xf3, 0xea, 0x62, 0xa0, 0xa6, 0xf8, 0xab, 0xdf, 0xea, 0x77, 0xaf, 0x2f, 0x7b,
	0x6a, 0x5a, 0xff, 0x35, 0x0b, 0x87, 0x73, 0x2a, 0x71, 0xf7, 0x71, 0x90, 0x67, 0x00, 0xe1, 0x8c,
	0x5b, 0x22, 0xd4, 0x62, 0x43, 0x7f, 0x3b, 0x0b, 0x8d, 0x05, 0x14, 0x32, 0xa1, 0x62, 0x89, 0x35,
	0x64, 0x26, 0xad, 0x4f, 0x8b, 0x2e, 0x3e, 0xfd, 0x07, 0x3b, 0xf3, 0x10, 0xe2, 0x15, 0x16, 0x13,
	0x48, 0xb6, 0xb2, 0x6c, 0x2d, 0xde, 0xa1, 0x73, 0xa8, 0xc4, 0x4c, 0x49, 0x1c, 0x64, 0x84, 0x83,
	0x8f, 0x36, 0xd7, 0x34, 0x86, 0x19, 0x65, 0x09, 0x4a, 0xac, 0xcc, 0x2b, 0x28, 0x17, 0x40, 0x7c,
	0x42, 0x01, 0x1c, 0x3a, 0xfe, 0x90, 0xfc, 0x48, 0x86, 0x66, 0xec, 0x25, 0xc4, 0x6c, 0x4c, 0xb5,
	0x3d, 0xe1, 0xe3, 0xd9, 0x6e, 0x49, 0x74, 0xa4, 0x05, 0xc9, 0x92, 0x57, 0x1c, 0x2f, 0x33, 0x41,
	0xce, 0x9a, 0xa0, 0x6a, 0x02, 0x5a, 0xcf, 0x79, 0xc3, 0xd4, 0x3d, 0x59, 0xe6, 0xe4, 0x5b, 0xb2,
	0x5d, 0x98, 0xe8, 0x0b, 0xb8, 0xb7, 0x25, 0x9e, 0x0d, 0xcc, 0xdf, 0x3e, 0xdb, 0x27, 0x00, 0x57,
	0xc4, 0xf6, 0x88, 0xcf, 0x06, 0xd8, 0xde, 0x75, 0x2b, 0xe8, 0xa7, 0x90, 0x8f, 0x51, 0xe8, 0x38,
	0x5e, 0x91, 0x72, 0xa8, 0x3f, 0x58, 0x8b, 0x7f, 0x6e, 0x5d, 0x6e, 0x44, 0xfd, 0x2f, 0x65, 0x46,
	0xd3, 0x58, 0x16, 0xd3, 0xf4, 0x3e, 0x94, 0xc6, 0x98, 0x9a, 0x54, 0x5e, 0x4a, 0xa2, 0x16, 0x8c,
	0xe2, 0x18, 0xd3, 0x58, 0x8f, 0xa2, 0x13, 0x28, 0xcc, 0xc4, 0x59, 0xe1, 0x50, 0xdb, 0xe6, 0xd0,
	0x98, 0x69, 0xa2, 0xee, 0x7c, 0x5f, 0xc9, 0x7e, 0x37, 0xb6, 0xf5, 0x7b, 0x29, 0xa0, 0xfa, 0x12,
	0x5d, 0x13, 0x13, 0xd5, 0x53, 0x28, 0x6d, 0xeb, 0xe9, 0xa6, 0x6a, 0x67, 0x17, 0xaa, 0x7d, 0x93,
	0x13, 0xff, 0x84, 0x9e, 0xfc, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xa9, 0xf3, 0x38, 0x82, 0xb1, 0x0c,
	0x00, 0x00,
}
