input_features:
  - name: Title
    type: text
  - name: Description
    type: text

output_features:
  - name: ClassIndex
    type: category

trainer:
    # learning_rate: 0.0001
    # decay: True
    # decay_rate: 0.9
    # decay_steps: 30000
    # staircase: True
    epochs: 2