version: 1.0
name: allocine
huggingface_dataset_id: allocine
loader: hugging_face.HFLoader
description: |
  AlloCine: French movie review sentiment dataset. Binary positive/negative labels.
columns:
  - name: review
    type: text
  - name: label
    type: binary
output_features:
  - name: label
    type: binary
