version: 1.0
name: alpaca_gpt4
huggingface_dataset_id: vicgalle/alpaca-gpt4
loader: hugging_face.HFLoader
description: |
  Alpaca GPT-4: 52K instruction-following examples.
columns:
  - name: instruction
    type: text
  - name: input
    type: text
  - name: output
    type: text
output_features:
  - name: output
    type: text
