version: 1.0
name: cnn_dm_hf
huggingface_dataset_id: abisee/cnn_dailymail
huggingface_subsample: "3.0.0"
loader: hugging_face.HFLoader
description: |
  CNN/DailyMail (abisee): news article summarization, 3.0.0 version (287K examples).
columns:
  - name: article
    type: text
  - name: highlights
    type: text
output_features:
  - name: highlights
    type: text
