version: 1.0
name: diabetes_readmission
huggingface_dataset_id: imodels/diabetes-readmission
loader: hugging_face.HFLoader
description: 'Diabetes hospital readmission prediction

  '
columns:
- name: time_in_hospital
  type: number
- name: num_lab_procedures
  type: number
- name: num_procedures
  type: number
- name: num_medications
  type: number
- name: number_outpatient
  type: number
- name: number_emergency
  type: number
- name: number_inpatient
  type: number
- name: number_diagnoses
  type: number
- name: change
  type: number
- name: diabetesMed
  type: number
- name: race:AfricanAmerican
  type: number
- name: race:Asian
  type: number
- name: race:Caucasian
  type: number
- name: race:Hispanic
  type: number
- name: race:Other
  type: number
- name: gender:Female
  type: number
- name: gender:Male
  type: number
- name: age:70+
  type: number
- name: age:[0-10)
  type: number
- name: age:[10-20)
  type: number
- name: age:[20-50)
  type: number
- name: age:[50-70)
  type: number
- name: admission_type_id:Elective
  type: number
- name: admission_type_id:Emergency
  type: number
- name: admission_type_id:New Born
  type: number
- name: admission_type_id:Trauma Center
  type: number
- name: discharge_disposition_id:Discharged to Home
  type: number
- name: discharge_disposition_id:Other
  type: number
- name: admission_source_id:Emergency
  type: number
- name: admission_source_id:Other
  type: number
- name: admission_source_id:Referral
  type: number
- name: admission_source_id:Transfer
  type: number
- name: medical_specialty:Cardiology
  type: number
- name: medical_specialty:Emergency/Trauma
  type: number
- name: medical_specialty:Family/GeneralPractice
  type: number
- name: medical_specialty:Gastroenterology
  type: number
- name: medical_specialty:Hematology/Oncology
  type: number
- name: medical_specialty:InternalMedicine
  type: number
- name: medical_specialty:Nephrology
  type: number
- name: medical_specialty:ObstetricsandGynecology
  type: number
- name: medical_specialty:Orthopedics
  type: number
- name: medical_specialty:Other
  type: number
- name: medical_specialty:Psychiatry
  type: number
- name: medical_specialty:Pulmonology
  type: number
- name: medical_specialty:Radiology
  type: number
- name: medical_specialty:Surgery-Cardiovascular/Thoracic
  type: number
- name: medical_specialty:Surgery-General
  type: number
- name: medical_specialty:Urology
  type: number
- name: diag_1:Circulatory
  type: number
- name: diag_1:Diabetes
  type: number
- name: diag_1:Digestive
  type: number
- name: diag_1:Genitourinary
  type: number
- name: diag_1:Infectious
  type: number
- name: diag_1:Injury
  type: number
- name: diag_1:Mental
  type: number
- name: diag_1:Musculoskeletal
  type: number
- name: diag_1:Neoplasms
  type: number
- name: diag_1:Non-diabetes endocrine/metabolic
  type: number
- name: diag_1:Other
  type: number
- name: diag_1:Respiratory
  type: number
- name: diag_1:Skin
  type: number
- name: diag_2:Circulatory
  type: number
- name: diag_2:Diabetes
  type: number
- name: diag_2:Digestive
  type: number
- name: diag_2:Genitourinary
  type: number
- name: diag_2:Infectious
  type: number
- name: diag_2:Injury
  type: number
- name: diag_2:Mental
  type: number
- name: diag_2:Musculoskeletal
  type: number
- name: diag_2:Neoplasms
  type: number
- name: diag_2:Non-diabetes endocrine/metabolic
  type: number
- name: diag_2:Other
  type: number
- name: diag_2:Respiratory
  type: number
- name: diag_2:Skin
  type: number
- name: diag_3:Circulatory
  type: number
- name: diag_3:Diabetes
  type: number
- name: diag_3:Digestive
  type: number
- name: diag_3:Genitourinary
  type: number
- name: diag_3:Infectious
  type: number
- name: diag_3:Injury
  type: number
- name: diag_3:Mental
  type: number
- name: diag_3:Musculoskeletal
  type: number
- name: diag_3:Neoplasms
  type: number
- name: diag_3:Non-diabetes endocrine/metabolic
  type: number
- name: diag_3:Other
  type: number
- name: diag_3:Respiratory
  type: number
- name: diag_3:Skin
  type: number
- name: metformin:Down
  type: number
- name: metformin:No
  type: number
- name: metformin:Steady
  type: number
- name: metformin:Up
  type: number
- name: repaglinide:Down
  type: number
- name: repaglinide:No
  type: number
- name: repaglinide:Steady
  type: number
- name: repaglinide:Up
  type: number
- name: nateglinide:Down
  type: number
- name: nateglinide:No
  type: number
- name: nateglinide:Steady
  type: number
- name: nateglinide:Up
  type: number
- name: chlorpropamide:Down
  type: number
- name: chlorpropamide:No
  type: number
- name: chlorpropamide:Steady
  type: number
- name: chlorpropamide:Up
  type: number
- name: glimepiride:Down
  type: number
- name: glimepiride:No
  type: number
- name: glimepiride:Steady
  type: number
- name: glimepiride:Up
  type: number
- name: glipizide:Down
  type: number
- name: glipizide:No
  type: number
- name: glipizide:Steady
  type: number
- name: glipizide:Up
  type: number
- name: glyburide:Down
  type: number
- name: glyburide:No
  type: number
- name: glyburide:Steady
  type: number
- name: glyburide:Up
  type: number
- name: pioglitazone:Down
  type: number
- name: pioglitazone:No
  type: number
- name: pioglitazone:Steady
  type: number
- name: pioglitazone:Up
  type: number
- name: rosiglitazone:Down
  type: number
- name: rosiglitazone:No
  type: number
- name: rosiglitazone:Steady
  type: number
- name: rosiglitazone:Up
  type: number
- name: acarbose:Down
  type: number
- name: acarbose:No
  type: number
- name: acarbose:Steady
  type: number
- name: acarbose:Up
  type: number
- name: miglitol:Down
  type: number
- name: miglitol:No
  type: number
- name: miglitol:Steady
  type: number
- name: miglitol:Up
  type: number
- name: tolazamide:No
  type: number
- name: tolazamide:Steady
  type: number
- name: tolazamide:Up
  type: number
- name: insulin:Down
  type: number
- name: insulin:No
  type: number
- name: insulin:Steady
  type: number
- name: insulin:Up
  type: number
- name: glyburide-metformin:Down
  type: number
- name: glyburide-metformin:No
  type: number
- name: glyburide-metformin:Steady
  type: number
- name: glyburide-metformin:Up
  type: number
- name: A1Cresult:>7
  type: number
- name: A1Cresult:>8
  type: number
- name: A1Cresult:None
  type: number
- name: A1Cresult:Norm
  type: number
- name: max_glu_serum:>200
  type: number
- name: max_glu_serum:>300
  type: number
- name: max_glu_serum:None
  type: number
- name: max_glu_serum:Norm
  type: number
- name: readmitted
  type: category
output_features:
- name: readmitted
  type: category
