version: 1.0
name: europarl_el_en
huggingface_dataset_id: Helsinki-NLP/europarl
huggingface_subsample: el-en
loader: translation_loader.EuroparlElEnLoader
description: |
  Europarl: European Parliament proceedings Greek-English translation.
columns:
  - name: el
    type: text
  - name: en
    type: text
output_features:
  - name: en
    type: text
