version: 1.0
name: food101
huggingface_dataset_id: ethz/food101
loader: hugging_face.HFLoader
description: |
  Food-101; 101-class food image classification
columns:
  - name: image
    type: image
  - name: label
    type: category
output_features:
  - name: label
    type: category
