version: 1.0
name: fsd50k
huggingface_dataset_id: Fhrozen/FSD50k
loader: hugging_face.HFLoader
description: |
  FSD50K; Freesound Dataset 50k; 200-class audio event classification
columns:
  - name: audio
    type: audio
  - name: label
    type: category
output_features:
  - name: label
    type: category
