version: 1.0
name: gtsrb
huggingface_dataset_id: tanganke/gtsrb
loader: hugging_face.HFLoader
description: |
  GTSRB; German Traffic Sign Recognition Benchmark; 43 classes
columns:
  - name: image
    type: image
  - name: label
    type: category
output_features:
  - name: label
    type: category
