version: 1.0
name: iris
download_urls: https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv
sha256:
  iris.csv: 9cc1c345c71bcc9b486b74cbf6063fa66f4bb5e0f603a4b3c3471ec2e5e8e355
description: |
  Iris Dataset
  https://archive.ics.uci.edu/ml/datasets/Iris
columns:
  - name: sepal_length_cm
    type: number
  - name: sepal_width_cm
    type: number
  - name: petal_length_cm
    type: number
  - name: petal_width_cm
    type: number
  - name: class
    type: category
output_features:
  - name: class
    type: category
