version: 1.0
name: iris
download_urls: https://archive.ics.uci.edu/static/public/53/iris.zip
sha256:
  iris.zip: d11fe30213d36434a0879aab7cb00ce3c812eb7ba2495874438abff7b7b762e9
description: |
  Iris Dataset
  https://archive.ics.uci.edu/dataset/53/iris.zip
columns:
  - name: sepal_length_cm
    type: number
  - name: sepal_width_cm
    type: number
  - name: petal_length_cm
    type: number
  - name: petal_width_cm
    type: number
  - name: class
    type: category
output_features:
  - name: class
    type: category
