version: 1.0
name: legalbench
huggingface_dataset_id: nguha/legalbench
huggingface_subsample: contract_nli_confidentiality_of_agreement
loader: hugging_face.HFLoader
description: |
  LegalBench; legal reasoning tasks including NLI on contracts
columns:
  - name: index
    type: category
  - name: answer
    type: text
  - name: text
    type: text
  - name: document_name
    type: text
output_features:
  - name: answer
    type: text
