version: 1.0
name: mteb_massive_scenario_hu
huggingface_dataset_id: mteb/massive_scenario
huggingface_subsample: "hu"
loader: hugging_face.HFLoader
description: |
  MTEB MASSIVE Scenario Classification (Hungarian): task-oriented dialog scenario prediction.
columns:
  - name: text
    type: text
  - name: label
    type: category
output_features:
  - name: label
    type: category
