version: 1.0
name: mteb_sts17_es
huggingface_dataset_id: mteb/sts17-crosslingual-sts
huggingface_subsample: es-en
loader: hugging_face.HFLoader
description: |
  MTEB STS17 (Spanish-English): cross-lingual semantic textual similarity.
columns:
  - name: sentence1
    type: text
  - name: sentence2
    type: text
  - name: score
    type: number
output_features:
  - name: score
    type: number
