version: 1.0
name: mteb_mtop_intent_en
huggingface_dataset_id: mteb/MTOPIntentClassification
huggingface_subsample: en
loader: hugging_face.HFLoader
description: |
  MTEB MTOP Intent Classification (English): task-oriented dialog intent prediction.
columns:
  - name: text
    type: text
  - name: label
    type: category
output_features:
  - name: label
    type: category
