version: 1.0
name: mteb_naija_senti_yor
huggingface_dataset_id: mteb/NaijaSenti
huggingface_subsample: yor
loader: hugging_face.HFLoader
description: |
  MTEB NaijaSenti (Yoruba): Nigerian language sentiment classification.
columns:
  - name: text
    type: text
  - name: label
    type: category
output_features:
  - name: label
    type: category
