version: 1.0
name: mteb_georeview
huggingface_dataset_id: mteb/GeoreviewClassification
loader: hugging_face.HFLoader
description: |
  MTEB Georeview Classification: Russian-language geographic review sentiment classification.
columns:
  - name: text
    type: text
  - name: label
    type: category
output_features:
  - name: label
    type: category
