version: 1.0
name: mteb_massive_intent_th
huggingface_dataset_id: mteb/massive_intent
huggingface_subsample: "th"
loader: hugging_face.HFLoader
description: |
  MTEB MASSIVE Intent Classification (Thai): task-oriented dialog intent prediction.
columns:
  - name: text
    type: text
  - name: label
    type: category
output_features:
  - name: label
    type: category
