version: 1.0
name: mteb_online_shopping
huggingface_dataset_id: mteb/OnlineShopping
loader: hugging_face.HFLoader
description: |
  MTEB OnlineShopping: Chinese online shopping review sentiment classification.
columns:
  - name: text
    type: text
  - name: label
    type: category
output_features:
  - name: label
    type: category
