version: 1.0
name: qqp
huggingface_dataset_id: nyu-mll/glue
huggingface_subsample: qqp
loader: hugging_face.HFLoader
description: |
  Quora Question Pairs; whether two questions are semantically equivalent
columns:
  - name: question1
    type: text
  - name: question2
    type: text
  - name: label
    type: category
  - name: idx
    type: category
output_features:
  - name: label
    type: category
