version: 1.0
name: samsum
huggingface_dataset_id: knkarthick/samsum
loader: hugging_face.HFLoader
description: |
  SAMSum: dialogue summarization. 14K train examples.
columns:
  - name: dialogue
    type: text
  - name: summary
    type: text
output_features:
  - name: summary
    type: text
