version: 1.0
name: scotus_classification
huggingface_dataset_id: coastalcph/lex_glue
huggingface_subsample: scotus
loader: hugging_face.HFLoader
description: |
  LexGLUE SCOTUS; US Supreme Court opinion issue area classification
columns:
  - name: text
    type: text
  - name: label
    type: category
output_features:
  - name: label
    type: category
