version: 1.0
name: setfit_subj
huggingface_dataset_id: SetFit/subj
loader: hugging_face.HFLoader
description: |
  SetFit SUBJ: subjectivity detection (subjective vs objective sentences).
columns:
  - name: text
    type: text
  - name: label
    type: binary
output_features:
  - name: label
    type: binary
