version: 1.0
name: sts14
huggingface_dataset_id: mteb/sts14-sts
loader: hugging_face.HFLoader
description: |
  STS 2014: semantic textual similarity. 3750 test examples.
columns:
  - name: sentence1
    type: text
  - name: sentence2
    type: text
  - name: score
    type: number
output_features:
  - name: score
    type: number
