version: 1.0
name: sts16
huggingface_dataset_id: mteb/sts16-sts
loader: hugging_face.HFLoader
description: |
  STS 2016: semantic textual similarity. 1186 test examples.
columns:
  - name: sentence1
    type: text
  - name: sentence2
    type: text
  - name: score
    type: number
output_features:
  - name: score
    type: number
