version: 1.0
name: sts17
huggingface_dataset_id: mteb/sts17-crosslingual-sts
loader: hugging_face.HFLoader
description: |
  STS 2017: cross-lingual STS. 5346 test examples.
columns:
  - name: sentence1
    type: text
  - name: sentence2
    type: text
  - name: score
    type: number
  - name: lang
    type: category
output_features:
  - name: score
    type: number
