version: 1.0
name: winobias
huggingface_dataset_id: uclanlp/wino_bias
huggingface_subsample: type1_anti
loader: ner_loader.WinobiasLoader
description: |
  WinoBias coreference gender bias. Sentence → label.
columns:
  - name: sentence
    type: text
  - name: ner_tags
    type: sequence
output_features:
  - name: ner_tags
    type: sequence
